/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * A frame that contains a news article with a headline and content. Allows
 * the user to guess whether the article is misleading or accurate.
 * 
 * @author Berke Eren and Zi Cheng Qiu.
 * @version 1.0
 * @since 2025-05-21
 */
public class ArticleFrame extends javax.swing.JFrame {
    // Initialize instance variable.
    private Quiz quiz;
    
    /**
     * A constructor with no parameters that sets the background colour of the frame to blue.
     */
    public ArticleFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(0, 166, 255));
    }
    
    /**
     * A parameterized constructor that sets the background colour of the frame to blue.
     * 
     * @param quiz the quiz that this frame is a part of
     */
    public ArticleFrame(Quiz quiz) {
        this.quiz = quiz;
        initComponents();
        getContentPane().setBackground(new java.awt.Color(0, 166, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headline = new javax.swing.JLabel();
        additionalInfoHeader = new javax.swing.JLabel();
        misleadingButton = new javax.swing.JToggleButton();
        reliableButton1 = new javax.swing.JToggleButton();
        score = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        content = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        additionalInfoLabel = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headline.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        additionalInfoHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        misleadingButton.setBackground(new java.awt.Color(255, 51, 51));
        misleadingButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        misleadingButton.setText("Misleading");
        misleadingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misleadingButtonActionPerformed(evt);
            }
        });

        reliableButton1.setBackground(new java.awt.Color(0, 255, 51));
        reliableButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reliableButton1.setText("Reliable");
        reliableButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reliableButton1ActionPerformed(evt);
            }
        });

        score.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        score.setToolTipText("");

        content.setColumns(20);
        content.setLineWrap(true);
        content.setRows(5);
        content.setWrapStyleWord(true);
        jScrollPane1.setViewportView(content);

        additionalInfoLabel.setColumns(20);
        additionalInfoLabel.setLineWrap(true);
        additionalInfoLabel.setRows(5);
        additionalInfoLabel.setWrapStyleWord(true);
        jScrollPane2.setViewportView(additionalInfoLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(headline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(273, 273, 273)
                                .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(additionalInfoHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reliableButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(misleadingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(headline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(score, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(additionalInfoHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(reliableButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(misleadingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reliableButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reliableButton1ActionPerformed
        // Display the results of the guess.
        quiz.displayResults(true);
    }//GEN-LAST:event_reliableButton1ActionPerformed

    private void misleadingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misleadingButtonActionPerformed
        // Display the results of the guess.
        quiz.displayResults(false);
    }//GEN-LAST:event_misleadingButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArticleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArticleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArticleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArticleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArticleFrame().setVisible(true);
            }
        });
    }
    
    /**
     * Displays the news article including its headline and content.
     * Also displays the score, and any additional context.
     * 
     * @param article the article to display
     * @param score the user's score
     */
    public void displayArticle(NewsArticle article, int score) {
        // Display headline and content.
        headline.setText(article.getHeadline());
        content.setText(article.getContent());
        // Display score.
        this.score.setText(score + "/" + quiz.getNumArticles());
        // Display additional information, if the article has it.
        if (!article.getAdditionalInformation().equals("")) {
            additionalInfoHeader.setText("Additional Information");
            additionalInfoLabel.setText(article.getAdditionalInformation());    
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel additionalInfoHeader;
    private javax.swing.JTextArea additionalInfoLabel;
    private javax.swing.JTextArea content;
    private javax.swing.JLabel headline;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton misleadingButton;
    private javax.swing.JToggleButton reliableButton1;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
